### ISSUE TITLE
TapJoy Version 11

### ISSUE THREAD

**Issue by julien-its** [shaxxx/Xamarin.Tapjoy#1]
Hi,

Do you have the binding for TapJoy version 11 ?

Thank you

**Comment by shaxxx** [comment]
No. But as far as I can remember it shouldn't be too dificult to create one.
I specifically wanted older Tapjoy because new one with all the Google Play dependencies was kind of bloatware for me and required higher min SDK version than this one.

**Comment by julien-its** [comment]
Ok, i'm trying to do it and I have an error of ambiguity definition for a var in a class with same name.

Here the first class:

` public partial class VideoErrorEventArgs : global::System.EventArgs {

		public VideoErrorEventArgs (int p0)
		{
			this.p0 = p0;
		}

		int p0;
		public int P0 {
			get { return p0; }
		}
	}`

And the second class with same name and same p0 var : 

`public partial class VideoErrorEventArgs : global::System.EventArgs {

		public VideoErrorEventArgs (global::Com.Tapjoy.TJPlacement p0, string p1)
		{
			this.p0 = p0;
			this.p1 = p1;
		}

		global::Com.Tapjoy.TJPlacement p0;
		public global::Com.Tapjoy.TJPlacement P0 {
			get { return p0; }
		}

		string p1;
		public string P1 {
			get { return p1; }
		}
	}`

I'm trying to resolve with the metadata.xml file, but i don't find how exactly I can do. 
Do you have an idea about it ? 

Thank you in advance
Julien

**Comment by shaxxx** [comment]
Well, it's been a while since I was doing Xamarin bindings.
My general way of handling errors in bindings are
- try to hide/exclude method(s) that create problems 
- try to change method signatures and call original method in the new one

Keep in mind, you need to "bind" only methods and types used in C#.  
So if you're not using above types directly you can safely remove them in metadata.xml.
If you're still having problems why not create new git repository, upload your progress and then ask someone for help?

**Comment by julien-its** [comment]
Thank you for yours advises

I tried to remove the class with this

 <remove-node path="/api/package[@name='com.Tapjoy.VideoErrorEventArgs']" />
  <remove-node path="/api/package[@name='com.Tapjoy']/class[@name='VideoErrorEventArgs']" />
  <remove-node path="/api/package[@name='com.Tapjoy']/class[@name='ITJVideoListenerImplementor']" />

But still same problem.

I created a github : https://github.com/julien-its/xamarinTapJoyLink

There is a way to ask help publicly ?

Thank you

**Comment by julien-its** [comment]
This line works

<remove-node path="/api/package[@name='com.tapjoy']/interface[@name='TJVideoListener']/method[@name='onVideoError' and count(parameter)=1 and parameter[1][@type='int']]" />

I can build. But i don't know yet if I will need this method or not... lol

**Comment by julien-its** [comment]
This line works

`<remove-node path="/api/package[@name='com.tapjoy']/interface[@name='TJVideoListener']/method[@name='onVideoError' and count(parameter)=1 and parameter[1][@type='int']]" />`

But i don't know yet if i will need it later or not...

So far i can compile with this

**Comment by shaxxx** [comment]
If you don't need to handle onVideoError from your C# code that's fine, if you do I believe just renaming parameter will work.

`  <attr path="/api/package[@name='com.tapjoy']/interface[@name='TJVideoListener']/method[@name='onVideoError']/parameter[@name='p0']" name="name">args</attr>`

**Comment by julien-its** [comment]
Yes you're right, renaming parameter is beter. And works when referencing the dll in a android project. With my solution it doesn't work.

Thank you!
